repoRoot = fileparts(mfilename('fullpath'));

avaRoot = fullfile(repoRoot, 'vendor', 'ava');
avaFdmRoot = fullfile(avaRoot, 'FDM-package');
compatRoot = fullfile(repoRoot, 'matlab', 'ava_compat');
inputCsv = fullfile(repoRoot, 'fixtures', 'input.csv');

assert(isfolder(avaRoot), ...
    'AVA source directory was not found: %s', avaRoot);
assert(isfolder(avaFdmRoot), ...
    'AVA FDM directory was not found: %s', avaFdmRoot);
assert(isfolder(compatRoot), ...
    'AVA compatibility directory was not found: %s', compatRoot);
assert(isfile(inputCsv), ...
    'Input fixture was not found: %s', inputCsv);

% Patch only AVA's broken zero/single-passage postprocessing functions.
compatibilityFiles = { ...
    'vibratoCandidates.m', ...
    'getVibratoParaFDM.m' ...
};

for fileIndex = 1:numel(compatibilityFiles)
    filename = compatibilityFiles{fileIndex};

    sourceFile = fullfile(compatRoot, filename);
    destinationFile = fullfile(avaFdmRoot, filename);

    assert(isfile(sourceFile), ...
        'Compatibility file was not found: %s', sourceFile);

    [copied, message] = copyfile( ...
        sourceFile, ...
        destinationFile, ...
        'f' ...
    );

    assert(copied, ...
        'Could not install AVA compatibility file %s: %s', ...
        filename, ...
        message);
end

addpath(fullfile(repoRoot, 'matlab'));
addpath(genpath(avaRoot));

set(groot, 'defaultFigureVisible', 'off');

previousFolder = cd(repoRoot);
restoreFolder = onCleanup(@() cd(previousFolder));

ava_ci_entry( ...
    'fixtures/input.csv', ...
    'results/ava_native.csv', ...
    'results/ava_native.mat' ...
);