function ava_ci_entry(inputCsv, outputCsv, outputMat)
%AVA_CI_ENTRY Run released AVA FDM+DT and FDM+BR on a MIDI pitch contour.

    harnessRoot = pwd;
    inputCsv = fullfile(harnessRoot, char(inputCsv));
    outputCsv = fullfile(harnessRoot, char(outputCsv));
    outputMat = fullfile(harnessRoot, char(outputMat));

    input = readtable(inputCsv);
    originalTime = input.time(:);
    pitchMidi = input.pitch_midi(:);

    if numel(originalTime) < 2
        error('The input contour must contain at least two frames.');
    end

    % AVA expects frequency in Hz, then performs its own freqToMidi step.
    originalPitch = 440 .* 2.^((pitchMidi - 69) ./ 12);

    % Preserve AVA's unvoiced convention. Its freqToMidi maps frequencies
    % below 8.18 Hz to MIDI zero.
    originalPitch(~isfinite(originalPitch)) = 0;

    outputFolder = fileparts(outputCsv);
    if ~exist(outputFolder, 'dir')
        mkdir(outputFolder);
    end

    % BayesRule loads its released density files by relative filename.
    avaFdmFolder = fileparts(which('vibratoDetectFunc'));
    previousFolder = pwd;
    restoreFolder = onCleanup(@() cd(previousFolder));
    cd(avaFdmFolder);

    rateLimits = [4, 9];
    extentLimits = [0.10, NaN];

    [dtCandidates, dtParameters, timeF, fdmOutput] = ...
        vibratoDetectFunc( ...
            originalPitch, ...
            originalTime, ...
            rateLimits, ...
            extentLimits ...
        );

    timeF = timeF(:);
    rateHz = fdmOutput(:, 1);
    extentSemitones = fdmOutput(:, 2);

    dtDetected = markCandidates(timeF, dtCandidates);

    % vibratoDetectFunc computes BR internally but does not expose it. Load
    % the released KDE objects to export the exact component probabilities,
    % then verify our reconstruction against the released BayesRule function.
    rateVibratoModel = load('pdVRFDM.mat', 'pdVR');
    rateNonvibratoModel = load('pdNRFDM.mat', 'pdNR');
    extentVibratoModel = load('pdVAFDM.mat', 'pdVA');
    extentNonvibratoModel = load('pdNAFDM.mat', 'pdNA');
    brRatePdfVibrato = pdf(rateVibratoModel.pdVR, rateHz);
    brRatePdfNonvibrato = pdf(rateNonvibratoModel.pdNR, rateHz);
    brExtentPdfVibrato = pdf(extentVibratoModel.pdVA, extentSemitones);
    brExtentPdfNonvibrato = pdf(extentNonvibratoModel.pdNA, extentSemitones);
    brRatePosterior = posterior_component( ...
        brRatePdfVibrato * 0.1, brRatePdfNonvibrato * 0.1);
    brExtentPosterior = posterior_component( ...
        brExtentPdfVibrato * 0.01, brExtentPdfNonvibrato * 0.01);
    brProbability = brRatePosterior .* brExtentPosterior;
    brRawDetected = brProbability >= 0.25;

    brIndicatorRaw = BayesRule( ...
        rateHz.', ...
        extentSemitones.', ...
        2.5, ...
        0.25, ...
        'FDM' ...
    );
    assert(isequal(brRawDetected, (brIndicatorRaw(:) == 2.5)), ...
        'Reconstructed BR probability disagrees with released BayesRule.m');
    brIndicator = deleteOutlier(brIndicatorRaw, 2.5);

    frameCriterion = 5;
    brCandidates = vibratoCandidates( ...
        brIndicator, ...
        2.5, ...
        frameCriterion, ...
        timeF ...
    );

    if ~isempty(brCandidates)
        brCandidates(:, 3) = brCandidates(:, 2) - brCandidates(:, 1);
        brCandidates = NotePruning(brCandidates, 0.25);
    end

    brDetected = markCandidates(timeF, brCandidates);

    nativeFrames = table( ...
        timeF, ...
        rateHz, ...
        extentSemitones, ...
        dtDetected, ...
        brRatePdfVibrato, ...
        brRatePdfNonvibrato, ...
        brExtentPdfVibrato, ...
        brExtentPdfNonvibrato, ...
        brRatePosterior, ...
        brExtentPosterior, ...
        brProbability, ...
        brRawDetected, ...
        brDetected, ...
        'VariableNames', { ...
            'time', ...
            'rate_hz', ...
            'extent_semitones', ...
            'dt_detected', ...
            'br_rate_pdf_vibrato', ...
            'br_rate_pdf_nonvibrato', ...
            'br_extent_pdf_vibrato', ...
            'br_extent_pdf_nonvibrato', ...
            'br_rate_posterior', ...
            'br_extent_posterior', ...
            'br_probability', ...
            'br_raw_detected', ...
            'br_detected' ...
        } ...
    );

    writetable(nativeFrames, outputCsv);

    save( ...
        outputMat, ...
        'originalTime', ...
        'originalPitch', ...
        'timeF', ...
        'fdmOutput', ...
        'dtCandidates', ...
        'dtParameters', ...
        'dtDetected', ...
        'brRatePdfVibrato', ...
        'brRatePdfNonvibrato', ...
        'brExtentPdfVibrato', ...
        'brExtentPdfNonvibrato', ...
        'brRatePosterior', ...
        'brExtentPosterior', ...
        'brProbability', ...
        'brRawDetected', ...
        'brIndicatorRaw', ...
        'brIndicator', ...
        'brCandidates', ...
        'brDetected' ...
    );
end


function posterior = posterior_component(vibratoDensity, nonvibratoDensity)
    posterior = (vibratoDensity * 0.5) ./ ( ...
        vibratoDensity * 0.5 + nonvibratoDensity * 0.5 ...
    );
end


function mask = markCandidates(timeF, candidates)
    mask = false(size(timeF));

    for index = 1:size(candidates, 1)
        mask = mask | ( ...
            timeF >= candidates(index, 1) ...
            & timeF <= candidates(index, 2) ...
        );
    end
end
