function ava_ci_entry(inputCsv, outputCsv, outputMat)
%AVA_CI_ENTRY Run released AVA FDM+DT and FDM+BR on a MIDI pitch contour.

    harnessRoot = pwd;
    inputCsv = fullfile(harnessRoot, char(inputCsv));
    outputCsv = fullfile(harnessRoot, char(outputCsv));
    outputMat = fullfile(harnessRoot, char(outputMat));

    input = readtable(inputCsv);
    originalTime = input.time(:);
    pitchMidi = input.pitch_midi(:);

    if numel(originalTime) < 2
        error("The input contour must contain at least two frames.");
    end

    % AVA expects frequency in Hz, then performs its own freqToMidi step.
    originalPitch = 440 .* 2.^((pitchMidi - 69) ./ 12);

    % Preserve AVA's unvoiced convention. Its freqToMidi maps frequencies
    % below 8.18 Hz to MIDI zero.
    originalPitch(~isfinite(originalPitch)) = 0;

    outputFolder = fileparts(outputCsv);
    if ~exist(outputFolder, "dir")
        mkdir(outputFolder);
    end

    % BayesRule loads its released density files by relative filename.
    avaFdmFolder = fileparts(which("vibratoDetectFunc"));
    previousFolder = pwd;
    restoreFolder = onCleanup(@() cd(previousFolder));
    cd(avaFdmFolder);

    rateLimits = [4, 9];
    extentLimits = [0.10, NaN];

    [dtCandidates, dtParameters, timeF, fdmOutput] = ...
        vibratoDetectFunc( ...
            originalPitch, ...
            originalTime, ...
            rateLimits, ...
            extentLimits ...
        );

    timeF = timeF(:);
    rateHz = fdmOutput(:, 1);
    extentSemitones = fdmOutput(:, 2);

    dtDetected = markCandidates(timeF, dtCandidates);

    % vibratoDetectFunc computes BR internally but does not expose it.
    % Reapply the released BR and passage functions to the exact FDM output.
    brIndicator = BayesRule( ...
        rateHz.', ...
        extentSemitones.', ...
        2.5, ...
        0.25, ...
        'FDM' ...
    );
    brIndicator = deleteOutlier(brIndicator, 2.5);

    frameCriterion = 5;
    brCandidates = vibratoCandidates( ...
        brIndicator, ...
        2.5, ...
        frameCriterion, ...
        timeF ...
    );

    if ~isempty(brCandidates)
        brCandidates(:, 3) = brCandidates(:, 2) - brCandidates(:, 1);
        brCandidates = NotePruning(brCandidates, 0.25);
    end

    brDetected = markCandidates(timeF, brCandidates);

    nativeFrames = table( ...
        timeF, ...
        rateHz, ...
        extentSemitones, ...
        dtDetected, ...
        brDetected, ...
        "VariableNames", { ...
            "time", ...
            "rate_hz", ...
            "extent_semitones", ...
            "dt_detected", ...
            "br_detected" ...
        } ...
    );

    writetable(nativeFrames, outputCsv);

    save( ...
        outputMat, ...
        "originalTime", ...
        "originalPitch", ...
        "timeF", ...
        "fdmOutput", ...
        "dtCandidates", ...
        "dtParameters", ...
        "dtDetected", ...
        "brIndicator", ...
        "brCandidates", ...
        "brDetected" ...
    );
end


function mask = markCandidates(timeF, candidates)
    mask = false(size(timeF));

    for index = 1:size(candidates, 1)
        mask = mask | ( ...
            timeF >= candidates(index, 1) ...
            & timeF <= candidates(index, 2) ...
        );
    end
end