function export_ava_br_models(avaFdmFolder, outputFolder)
%EXPORT_AVA_BR_MODELS Export AVA's released KDE objects as plain data.
% The released pd*FDM.mat files contain prob.KernelDistribution objects,
% which scipy.io cannot deserialize. This function exports every sufficient
% parameter needed to reconstruct their univariate KDE PDFs in Python, plus
% native MATLAB reference PDFs and Bayes decisions for parity tests.

    avaFdmFolder = char(avaFdmFolder);
    outputFolder = char(outputFolder);
    if ~exist(outputFolder, 'dir')
        mkdir(outputFolder);
    end

    specs = { ...
        'pdVR', 'pdVRFDM.mat', 'rate_vibrato'; ...
        'pdNR', 'pdNRFDM.mat', 'rate_nonvibrato'; ...
        'pdVA', 'pdVAFDM.mat', 'extent_vibrato'; ...
        'pdNA', 'pdNAFDM.mat', 'extent_nonvibrato' ...
    };
    modelCount = size(specs, 1);
    objects = cell(modelCount, 1);
    brModels = struct();

    modelName = cell(modelCount, 1);
    variableName = cell(modelCount, 1);
    sourceFile = cell(modelCount, 1);
    className = cell(modelCount, 1);
    distributionName = cell(modelCount, 1);
    kernel = cell(modelCount, 1);
    support = cell(modelCount, 1);
    bandwidth = zeros(modelCount, 1);
    sampleCount = zeros(modelCount, 1);
    effectiveSampleCount = zeros(modelCount, 1);
    censoredCount = zeros(modelCount, 1);
    isTruncated = false(modelCount, 1);

    for index = 1:modelCount
        variable = specs{index, 1};
        filename = specs{index, 2};
        label = specs{index, 3};
        modelPath = fullfile(avaFdmFolder, filename);
        assert(isfile(modelPath), 'AVA BR model was not found: %s', modelPath);

        loaded = load(modelPath, variable);
        assert(isfield(loaded, variable), ...
            'Expected variable %s in %s', variable, modelPath);
        distribution = loaded.(variable);
        assert(isa(distribution, 'prob.KernelDistribution'), ...
            'Expected %s to be prob.KernelDistribution, got %s', ...
            variable, class(distribution));

        plain = plain_kernel_model(distribution, label, variable, filename);
        objects{index} = distribution;
        brModels.(variable) = plain;

        samples = table( ...
            plain.samples, ...
            plain.frequency, ...
            plain.censored, ...
            'VariableNames', {'sample', 'frequency', 'censored'} ...
        );
        writetable(samples, fullfile(outputFolder, [variable, '_samples.csv']));

        modelName{index} = label;
        variableName{index} = variable;
        sourceFile{index} = filename;
        className{index} = plain.class_name;
        distributionName{index} = plain.distribution_name;
        kernel{index} = plain.kernel;
        support{index} = plain.support;
        bandwidth(index) = plain.bandwidth;
        sampleCount(index) = numel(plain.samples);
        effectiveSampleCount(index) = sum(plain.frequency);
        censoredCount(index) = sum(plain.censored);
        isTruncated(index) = plain.is_truncated;
    end

    modelManifest = table( ...
        modelName, ...
        variableName, ...
        sourceFile, ...
        className, ...
        distributionName, ...
        kernel, ...
        support, ...
        bandwidth, ...
        sampleCount, ...
        effectiveSampleCount, ...
        censoredCount, ...
        isTruncated, ...
        'VariableNames', { ...
            'model', ...
            'variable', ...
            'source_file', ...
            'class_name', ...
            'distribution_name', ...
            'kernel', ...
            'support', ...
            'bandwidth', ...
            'sample_count', ...
            'effective_sample_count', ...
            'censored_count', ...
            'is_truncated' ...
        } ...
    );
    writetable(modelManifest, fullfile(outputFolder, 'br_model_manifest.csv'));

    % The ranges mirror and refine the plotting ranges in AVA's released
    % probabilityDistribution2.m. These files are an independent native oracle
    % for the future Python KDE implementation.
    rateGrid = (-5.0:0.01:30.0).';
    extentGrid = (-2.0:0.001:3.0).';
    ratePdfVibrato = pdf(objects{1}, rateGrid);
    ratePdfNonvibrato = pdf(objects{2}, rateGrid);
    extentPdfVibrato = pdf(objects{3}, extentGrid);
    extentPdfNonvibrato = pdf(objects{4}, extentGrid);
    ratePosterior = posterior_component( ...
        ratePdfVibrato * 0.1, ratePdfNonvibrato * 0.1);
    extentPosterior = posterior_component( ...
        extentPdfVibrato * 0.01, extentPdfNonvibrato * 0.01);

    rateReference = table( ...
        rateGrid, ...
        ratePdfVibrato, ...
        ratePdfNonvibrato, ...
        ratePosterior, ...
        'VariableNames', { ...
            'rate_hz', ...
            'pdf_vibrato', ...
            'pdf_nonvibrato', ...
            'posterior_vibrato' ...
        } ...
    );
    extentReference = table( ...
        extentGrid, ...
        extentPdfVibrato, ...
        extentPdfNonvibrato, ...
        extentPosterior, ...
        'VariableNames', { ...
            'extent_semitones', ...
            'pdf_vibrato', ...
            'pdf_nonvibrato', ...
            'posterior_vibrato' ...
        } ...
    );
    writetable(rateReference, fullfile(outputFolder, 'br_rate_pdf_reference.csv'));
    writetable(extentReference, fullfile(outputFolder, 'br_extent_pdf_reference.csv'));

    % A compact Cartesian decision oracle catches posterior-combination and
    % threshold differences without requiring MATLAB during Python tests.
    decisionRateGrid = (0.0:0.1:20.0).';
    decisionExtentGrid = (0.0:0.01:3.0).';
    [decisionRates, decisionExtents] = ndgrid( ...
        decisionRateGrid, decisionExtentGrid);
    decisionRatePosteriorGrid = posterior_component( ...
        pdf(objects{1}, decisionRateGrid) * 0.1, ...
        pdf(objects{2}, decisionRateGrid) * 0.1 ...
    );
    decisionExtentPosteriorGrid = posterior_component( ...
        pdf(objects{3}, decisionExtentGrid) * 0.01, ...
        pdf(objects{4}, decisionExtentGrid) * 0.01 ...
    );
    [decisionRatePosterior, decisionExtentPosterior] = ndgrid( ...
        decisionRatePosteriorGrid, decisionExtentPosteriorGrid);
    decisionRates = decisionRates(:);
    decisionExtents = decisionExtents(:);
    decisionRatePosterior = decisionRatePosterior(:);
    decisionExtentPosterior = decisionExtentPosterior(:);
    decisionProbability = decisionRatePosterior .* decisionExtentPosterior;
    decisionDetected = decisionProbability >= 0.25;
    decisionReference = table( ...
        decisionRates, ...
        decisionExtents, ...
        decisionRatePosterior, ...
        decisionExtentPosterior, ...
        decisionProbability, ...
        decisionDetected, ...
        'VariableNames', { ...
            'rate_hz', ...
            'extent_semitones', ...
            'rate_posterior', ...
            'extent_posterior', ...
            'joint_probability', ...
            'detected' ...
        } ...
    );
    writetable( ...
        decisionReference, ...
        fullfile(outputFolder, 'br_decision_reference.csv') ...
    );

    save( ...
        fullfile(outputFolder, 'br_kde_models_plain.mat'), ...
        'brModels', ...
        'rateGrid', ...
        'ratePdfVibrato', ...
        'ratePdfNonvibrato', ...
        'ratePosterior', ...
        'extentGrid', ...
        'extentPdfVibrato', ...
        'extentPdfNonvibrato', ...
        'extentPosterior', ...
        '-v7' ...
    );

    provenance = struct();
    provenance.ava_source_repository = 'https://github.com/skx300/ava';
    provenance.ava_source_commit = ...
        '77e4dfe8affa6014112bdf23769b2a97dde0d2b7';
    provenance.matlab_version = version;
    provenance.exported_at = datestr(now, 30);
    provenance.prior_vibrato = 0.5;
    provenance.prior_nonvibrato = 0.5;
    provenance.probability_threshold = 0.25;
    provenance.rate_pdf_scale = 0.1;
    provenance.extent_pdf_scale = 0.01;
    provenance.indicator_sign = 2.5;
    provenance.frame_criterion = 5;
    provenance.duration_threshold_seconds = 0.25;
    provenance.notes = [ ...
        'Plain model data are exported from the released MATLAB objects; ', ...
        'reference PDFs and decisions are evaluated by MATLAB R2021a.' ...
    ];
    write_json( ...
        fullfile(outputFolder, 'br_export_provenance.json'), ...
        provenance ...
    );
end


function plain = plain_kernel_model(distribution, label, variable, filename)
    inputData = distribution.InputData;
    samples = double(inputData.data(:));
    if isempty(inputData.freq)
        frequency = ones(size(samples));
    else
        frequency = double(inputData.freq(:));
    end
    if isempty(inputData.cens)
        censored = false(size(samples));
    else
        censored = logical(inputData.cens(:));
    end
    assert(numel(frequency) == numel(samples), ...
        'Frequency length differs from sample length for %s', variable);
    assert(numel(censored) == numel(samples), ...
        'Censoring length differs from sample length for %s', variable);

    plain = struct();
    plain.name = label;
    plain.variable_name = variable;
    plain.source_file = filename;
    plain.class_name = class(distribution);
    plain.distribution_name = char(distribution.DistributionName);
    plain.kernel = char(distribution.Kernel);
    % KernelDistribution objects saved by older MATLAB releases used the
    % legacy spelling BandWidth. Newer releases document Bandwidth. Loading
    % AVA's 2015 objects in R2021a preserves the legacy property name.
    if isprop(distribution, 'Bandwidth')
        plain.bandwidth = double(distribution.Bandwidth);
    elseif isprop(distribution, 'BandWidth')
        plain.bandwidth = double(distribution.BandWidth);
    else
        available = strjoin(properties(distribution), ', ');
        error( ...
            'KernelDistribution has no bandwidth property. Available: %s', ...
            available ...
        );
    end
    % AVA's probabilityDistribution2.m created every released model with
    % fitdist(data, 'Kernel') and supplied neither Support nor truncation
    % options. Therefore all four models use MATLAB's unbounded, untruncated
    % defaults. The 2015 object stores Support as a version-specific internal
    % struct, so do not serialize that implementation detail.
    plain.support = 'unbounded';
    plain.is_truncated = false;
    plain.truncation = [-Inf; Inf];
    plain.samples = samples;
    plain.frequency = frequency;
    plain.censored = censored;
end


function posterior = posterior_component(vibratoDensity, nonvibratoDensity)
    posterior = (vibratoDensity * 0.5) ./ ( ...
        vibratoDensity * 0.5 + nonvibratoDensity * 0.5 ...
    );
end


function write_json(path, value)
    handle = fopen(path, 'w');
    assert(handle ~= -1, 'Could not open JSON output: %s', path);
    cleanup = onCleanup(@() fclose(handle));
    fwrite(handle, jsonencode(value), 'char');
    fwrite(handle, sprintf('\n'), 'char');
end
